config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  resources :gym_items, only: [:create, :edit, :update, :destroy]
  get 'gym_items/:id/toggle_use', to: 'gym_items#toggle_use', as: 'gym_items_toggle_use'
  post '/search',                 to: 'static_pages#search'
  get '/filter',                 to: 'static_pages#filter'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gym_item.rb
class GymItem < ApplicationRecord
	default_scope { order(name: :asc) }
	before_save :downcase_name_focus
	validates :name, 
			   presence: true,
			   length: { maximum: 255 },
			   uniqueness: { case_sensitive: false }
	validates :description,
			   presence: true
	validates :in_use, 
			   inclusion: [true, false]
	VALID_FOCUS_REGEX = /\A(cardio|strength-(?:lower|upper)|auxiliary)\z/i # Ensures only one focus is present case insensitively
	validates :focus,
	 		   presence: true,
	 		   length: { maximum: 255 },
	 		   format: { with: VALID_FOCUS_REGEX }


	private
		def downcase_name_focus
			self.name.downcase!
			self.focus.downcase!
		end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include GymItemsHelper
end

app/controllers/gym_items_controller.rb
class GymItemsController < ApplicationController

	def create
		@gym_item = GymItem.new(gym_item_params)
		if @gym_item.save 
			flash[:success] = 'New equipment successfuly acquired'
			redirect_to root_url, status: :see_other
		else 
			@gym_items = GymItem.paginate(page: params[:page], per_page: 5)
			render 'static_pages/home', status: :unprocessable_entity
		end 
	end 

	def edit
		@gym_item = GymItem.find(params[:id])
	end 

	def update
		@gym_item = GymItem.find(params[:id])
		if @gym_item.update gym_item_params 
			flash[:success] = 'Equipment updated'
			redirect_to root_url, status: :see_other
		else
			render 'edit', status: :unprocessable_entity
		end 
	end 

	def destroy 
		gym_item_to_destroy = GymItem.find(params[:id])
		gym_item_to_destroy.destroy
		flash[:success] = 'Removed Gym Equipment'
		redirect_to root_url, status: :see_other
	end

	def toggle_use
		@gym_item = GymItem.find(params[:id])
		@gym_item.toggle!(:in_use)
		redirect_to root_url, status: :see_other
	end

	private 
		def gym_item_params 
			params.require(:gym_item).permit(:name, :focus, :description)
		end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include StaticPagesHelper
  before_action :set_session, only: :home

  def home
    p session[:cardio]
    @gym_item = GymItem.new
    @gym_items = get_equipment
  end

  def search
    @gym_item = GymItem.new
    @gym_items = GymItem.where("name LIKE ?", "%#{params[:search][:name].downcase}%").paginate(page: params[:page])
    render 'home', status: :see_other
  end 

  def filter
    filter = params[:filter]
    session[filter] = !session[filter]
    redirect_to root_url, status: :see_other
  end 

  private 
    def set_session
      filters = [:cardio, :strength_lower, :strength_upper, :auxiliary]
      filters.each do |filter|
        session[filter] = true unless session[filter] == false
      end 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gym_items_helper.rb
module GymItemsHelper
	def get_full_focus short_focus 
		if short_focus == 'cardio'
			'Cardiovascular Health'
		elsif short_focus == 'strength-upper'
			'Strengthening upper body'
		elsif short_focus == 'strength-lower'
			'Strengthening lower body'
		else
			'For auxilliary training'
		end 
	end 

	def get_usage in_use
		if in_use
			'In usage'
		else
			'Not in usage'
		end 
	end 

	def get_focusses
		['cardio', 'strength-upper', 'strength-lower', 'auxiliary']
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def is_filter_on? filter
		if session[filter]
			'on'
		else
			'off'
		end
	end

	def get_equipment
		filters = []
		filters << 'cardio'		     if session[:cardio] 
		filters << 'strength-lower'  if session[:strength_lower] 
		filters << 'strength-upper'   if session[:strength_upper] 
		filters << 'auxiliary' 	     if session[:auxiliary]
		if filters.count == 4
			GymItem.paginate(per_page: 5, page: params[:page])
		else
			GymItem.where(focus: filters).paginate(per_page: 5, page: params[:page])
		end
	end

	def format_time(time_with_zone)
  		# Convert time to the desired format
  		time_with_zone.strftime('%d/%m/%y %I:%M%P')
	end

end

app/views/gym_items/_error_messages.html.erb
<% if object.errors.any? %>
	<div class='error-messages'>
		The form contains <%= pluralize(object.errors.count, "error") %>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/gym_items/_form.html.erb
<%= form_with( model: @gym_item) do |f| %>
	<%= render 'gym_items/error_messages', object: f.object %> 

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-entry' %>

	<%= f.label :focus %>
	<%= f.select :focus, get_focusses, include_blank: true, class: 'form-entry'  %>

	<%= f.label :description %>
	<%= f.text_area  :description, class: 'form-entry' %>

	<%= f.submit yield(:button_text), class: 'button' %>
<% end %>

<h3> Focus categories:</h3>
<ul>
	<li>cardio</li>
	<li>strength-upper</li>
	<li>strength-lower</li>
	<li>auxiliary</li>
</ul>

app/views/gym_items/_gym_item.html.erb
<li class='gym_item'>
	<span class='name'> <%= gym_item.name.titleize %> </span>
	<span class='description'> <%= gym_item.description %></span>
	<span class='key-info'> Focus: </span> <%= get_full_focus gym_item.focus %> |
	<span class='key-info'> Status:</span> <%= get_usage gym_item.in_use %> 
	<span class='times'> <span class='key-info'> Acquired on: </span> <%= format_time gym_item.created_at %> |<span class='key-info'> Last updated: </span> <%= format_time gym_item.updated_at %> </span>
	<span class='buttons'> <%= link_to 'toggle usage', gym_items_toggle_use_path(gym_item) %> | <%= link_to 'edit', edit_gym_item_path(gym_item) %> | <%= link_to 'remove', gym_item_path(gym_item), data: { "turbo-method": :delete, turbo_confirm: "You sure?" } %> </span>
</li>

app/views/gym_items/_new.html.erb
<%= form_with( model: @gym_item) do |f| %>
	<%= render 'gym_items/error_messages', object: f.object %> 

	<%= f.label :name %>
	<%= f.text_field :name, class: 'form-entry' %>

	<%= f.label :focus %>
	<%= f.text_field :focus, class: 'form-entry'  %>

	<%= f.label :description %>
	<%= f.text_area  :description, class: 'form-entry' %>

	<%= f.submit 'Get New Equipment', class: 'button' %>
<% end %>

<h3> Focus categories:</h3>
<ul>
	<li>cardio</li>
	<li>strength-upper</li>
	<li>strength-lower</li>
	<li>auxiliary</li>
</ul>

app/views/gym_items/edit.html.erb
<% provide(:title, 'Edit Equipment') %>
<% provide(:button_text, 'Save Changes') %>
<header>
	<h1 class='title'> Edit Equipment </h1>
</header>

<main class='edit'>
	<h2> <%= @gym_item.name.titleize %></h2>
	<%= render 'form' %>
</main>

app/views/layouts/_head.html.erb
<title><%= yield(:title) %></title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: message_type %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/_equipment.html.erb
<% if @gym_items.any? %>
	<ol class='gym_items'>
		<%= render @gym_items %>
	</ol>
	<%= will_paginate @gym_items, params: { controller: :static_pages, action: :home } %> <!-- Explicitly tell will_paginate which action to use, so no bug comes from using the create action and associated urls -->


<% else %>
	<h5> No Gym Equipment </h5>
<% end %>

app/views/static_pages/_search.html.erb
<%= form_with(url: search_path, scope: :search, class: 'search') do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.submit 'Search', class: 'button' %>
	<%= link_to 'Undo Search', root_url, class: "button" %>
<% end %>

<%= link_to 'Cardio', filter_path(filter: 'cardio'), 
								  class: "filter-button #{is_filter_on? :cardio}" %>
<%= link_to 'Strength-upper', filter_path(filter: 'strength_upper'), 
                     					  class: "filter-button #{is_filter_on? :strength_upper}" %>
<%= link_to 'Strength-lower', filter_path(filter: 'strength_lower'),
										  class: "filter-button #{is_filter_on? :strength_lower}" %>
<%= link_to 'Auxiliary', filter_path(filter: 'auxiliary'),
									 class: "filter-button #{is_filter_on? :auxiliary}" %>

app/views/static_pages/home.html.erb
<% provide(:title, 'Gym Inventory') %>
<% provide(:button_text, 'Get New Equipment') %>
<header>
	<h1 class='title'> Inventory </h1>
</header>

<main>
	<div class='new-equipment'>
		<%= render 'gym_items/form' %>
	</div>
	<div class='equipment'>
		<%= render 'static_pages/search' %>
		
		<%= render 'static_pages/equipment' %>
	</div>
</main>